// SPDX-FileCopyrightText: 2025 2025 INDUSTRIA DE DISEÑO TEXTIL S.A. (INDITEX S.A.)
//
// SPDX-License-Identifier: Apache-2.0

import { TemplateFormat } from "./types.js";

export const testTemplates: Record<string, TemplateFormat> = {
  template1: {
    version: "1.0",
    id: "template1",
    name: "Template 1 (Images)",
    nodes: [
      {
        id: "node1",
        x: 0,
        y: 0,
        width: 500,
        height: 880,
        kind: "image",
        editable: true,
        optional: false,
      },
      {
        id: "node2",
        x: 610,
        y: 0,
        width: 500,
        height: 880,
        kind: "image",
        editable: true,
        optional: false,
      },
      {
        id: "node3",
        x: 1220,
        y: 0,
        width: 500,
        height: 880,
        kind: "image",
        editable: true,
        optional: false,
      },
    ],
  },
  template2: {
    version: "1.0",
    id: "template2",
    name: "Template 2 (Empty frame)",
    nodes: [
      {
        id: "frame1",
        x: 0,
        y: 0,
        width: 1920,
        height: 1080,
        kind: "frame",
        children: [],
        editable: true,
        optional: false,
      },
    ],
  },
  template3: {
    version: "1.0",
    id: "template3",
    name: "Template 3 (Frame with images)",
    nodes: [
      {
        id: "frame1",
        x: 0,
        y: 0,
        width: 1920,
        height: 1080,
        kind: "frame",
        children: [
          {
            id: "node1",
            x: 100,
            y: 100,
            width: 500,
            height: 880,
            kind: "image",
            editable: true,
            optional: true,
          },
          {
            id: "node3",
            x: 1320,
            y: 100,
            width: 500,
            height: 880,
            kind: "image",
            editable: true,
            optional: true,
          },
          {
            id: "node2",
            x: 710,
            y: 100,
            width: 500,
            height: 880,
            kind: "image",
            editable: true,
            optional: true,
          },
        ],
        editable: true,
        optional: true,
      },
    ],
  },
  template4: {
    version: "1.0",
    id: "template4",
    name: "Template 4 (Frame with text)",
    nodes: [
      {
        id: "frame1",
        x: 0,
        y: 0,
        width: 1920,
        height: 1080,
        kind: "frame",
        children: [
          {
            id: "node1",
            x: 100,
            y: 216,
            width: 500,
            height: 650,
            kind: "image",
            editable: true,
            optional: true,
          },
          {
            id: "node3",
            x: 1320,
            y: 216,
            width: 500,
            height: 650,
            kind: "image",
            editable: true,
            optional: true,
          },
          {
            id: "node2",
            x: 711,
            y: 216,
            width: 500,
            height: 650,
            kind: "image",
            editable: true,
            optional: true,
          },
          {
            id: "title",
            x: 100,
            y: 100,
            width: 1720,
            height: 80,
            kind: "text",
            editable: true,
            optional: true,
            defaultProperties: {
              fontFamily: "Arial, sans-serif",
              fontSize: 80,
              align: "left",
              verticalAlign: "top",
              fill: "#000000",
              layout: "smart",
            },
          },
          {
            id: "subtitle",
            x: 100,
            y: 900,
            width: 1720,
            height: 80,
            kind: "text",
            editable: true,
            optional: true,
            defaultProperties: {
              fontFamily: "Arial, sans-serif",
              fontSize: 80,
              align: "center",
              verticalAlign: "bottom",
              fill: "#bbbbbb",
              layout: "smart",
            },
          },
        ],
        editable: true,
        optional: true,
      },
    ],
  },
  template5: {
    version: "1.0",
    id: "template5",
    name: "Template 5 (Frame portrait)",
    nodes: [
      {
        id: "frame1",
        x: 0,
        y: 0,
        width: 1080,
        height: 1920,
        kind: "frame",
        children: [
          {
            id: "image1",
            x: 100,
            y: 100,
            width: 420,
            height: 840,
            kind: "image",
            editable: true,
            optional: true,
          },
          {
            id: "image2",
            x: 560,
            y: 100,
            width: 420,
            height: 840,
            kind: "image",
            editable: true,
            optional: true,
          },
          {
            id: "image3",
            x: 100,
            y: 980,
            width: 420,
            height: 840,
            kind: "image",
            editable: true,
            optional: true,
          },
          {
            id: "image4",
            x: 560,
            y: 980,
            width: 420,
            height: 840,
            kind: "image",
            editable: true,
            optional: true,
          },
          {
            id: "imagecenter",
            x: 291,
            y: 711,
            width: 500,
            height: 500,
            kind: "image",
            editable: true,
            optional: true,
          },
        ],
        editable: true,
        optional: true,
      },
    ],
  },
};
