version = 1
SPDX-PackageName = "weavejs-backend"
SPDX-PackageSupplier = "2025 INDUSTRIA DE DISEÑO TEXTIL S.A. (INDITEX S.A.)"
SPDX-PackageDownloadLocation = "https://github.com/InditexTech/weavejs-backend"

[[annotations]]
path = [
    # root level licensing
    ".github/**",
    "images/**",
    "REUSE.toml",
    "repolinter.json",

    # repeated files licensing
    "**/.gitignore",
    "**/tsconfig.json",
    "**/package*.json",

    # code/ directory licensing
    "cleanup-storage/src/whitelist.json",
    "code/fonts/**",
    "code/.husky/**",
    "code/.prettierrc",
    "code/nodemon.json",
    "code/justfile",
    "code/.tool-versions",
    "code/tsconfig.base.json",
]
SPDX-FileCopyrightText = "2025 INDUSTRIA DE DISEÑO TEXTIL S.A. (INDITEX S.A.)"
SPDX-License-Identifier = "Apache-2.0"
